### ISSUE TITLE
Documentation tracker

### ISSUE THREAD

**Issue by mfornet** [mfornet/acmx#78]
Currently wiki has only basic setup, but the extension have grown and it is necessary to document all features. This issue will help keep track about everything that needs to be added to the documentation.

Wiki: https://github.com/mfornet/acmx/wiki

- [ ] Home
- [ ] Custom Checker
    Explain how to set up a custom checker for a problem
- [ ] Debug Test Case
    Steps to debug a solution on different languages.
    - [ ] C++
    - [ ] Python
    - [ ] Java
    - [ ] Rust
- [ ] FAQ
   - [ ] Multiple test case. How to add snippets to read multiple test cases. Builtin feature from vscode, not related to acmx.
   - [ ] Read and write from file. Use snippets to add relevant code, and compilation flags to simulate one behavior locally, and different behavior in the online judge.
   - [ ] Multiple solution. How to have multiple solution in the same workspace. After #73 
   - [ ] Smart copy. How to use smart copy to generate solutions that use custom library.
- [ ] File Structure
    Explain the structure of all folder and files created and relevant configurations to change it.
    - Location of contest + problems
    - Structure of a single problem (testcase, attic, config.json)
    - Location of `languages` folder
    - Location of templates
- [ ] Manage Test Cases
    How to create, remove and open a testcase. 
- [ ] Multiple Languages
    Explain about `language` folder and how to modify or create a new language profile.
- [ ] Settings and Commands
    Enumerate all settings and commands exposed by acmx and explain its function. Link to relevant documentation.
- [ ] Stress
    How to stress a solution against a generator and a brute force.

**Comment by mfornet** [comment]
- [ ] Add Side Bar for better organization (instead of Pages sorted lexicographically). See example here: https://github.com/Microsoft/vscode-wiki
- [ ] Use internal links with the markdown format [[ text | name ]]
